openapi: 3.1.0
info:
  title: Annuaire
  description: API d'accès à l'annuaire des professionnels de la rénovation énergétique
  version: 1.0.0
servers:
  - url: /annuaire
tags:
  - name: Accompagnateur
  - name: Auditeur
  - name: Espace Conseil
  - name: Professionnel
paths:
  /accompagnateurs:
    get:
      summary: Recherche une liste d'accompagnateurs
      description: Ce endpoint interroge l'opendata des établissements agréés Mon Accompagnateur Rénov'
      tags:
        - Accompagnateur
      parameters:
        - name: code_insee
          description: Filtre par couverture géographique des établissements MAR
          in: query
          schema:
            type: string
            pattern: ^(([0-8][0-9])|(9[0-5]))[0-9]{3}$
        - name: distance
          description: Filtre par distance du code insee
          in: query
          schema:
            type: integer
        - name: siren
          description: Filtre par numéro de SIREN
          in: query
          schema:
            $ref: "#/components/schemas/siren"
        - name: date
          description: Filtre par date d'agrément des établissements MAR
          in: query
          schema:
            type: string
            format: date
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/accompagnateur"
        "400":
          description: Bad request
  /accompagnateurs/{siret}:
    parameters:
      - name: siret
        description: Filtre par numéro de SIRET
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/siret"
      - name: date
        description: Filtre par date d'agrément des établissements MAR
        in: query
        schema:
          type: string
          format: date
    get:
      summary: Recherche un accompagnateur par son numéro de SIRET
      tags:
        - Accompagnateur
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/accompagnateur"
        "400":
          description: Bad request
        "404":
          description: Not found
  /auditeurs:
    get:
      summary: Recherche une liste d'auditeurs
      description: Ce endpoint interroge l'opendata des entreprises RGE
      tags:
        - Auditeur
      parameters:
        - name: code_insee
          description: Filtre par couverture géographique des établissements MAR
          in: query
          schema:
            type: string
            pattern: ^(([0-8][0-9])|(9[0-5]))[0-9]{3}$
        - name: distance
          description: Filtre par distance du code insee
          in: query
          schema:
            type: integer
        - name: siren
          description: Filtre par numéro de SIREN
          in: query
          schema:
            $ref: "#/components/schemas/siren"
        - name: date
          description: Filtre par date de qualification RGE
          in: query
          schema:
            type: string
            format: date
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/auditeur"
        "400":
          description: Bad request
  /auditeurs/{siret}:
    parameters:
      - name: siret
        description: Filtre par numéro de SIRET
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/siret"
      - name: date
        description: Filtre par date de qualification RGE
        in: query
        schema:
          type: string
          format: date
    get:
      summary: Recherche un auditeur par son numéro de SIRET
      tags:
        - Auditeur
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/auditeur"
        "400":
          description: Bad request
        "404":
          description: Not found
  /espaces-conseil:
    get:
      summary: Recherche une liste d'espaces conseils France Rénov'
      description: Ce endpoint interroge l'opendata de l'ADEME
      tags:
        - Espace Conseil
      parameters:
        - name: code_insee
          description: Filtre par couverture géographique des établissements MAR
          in: query
          schema:
            type: string
            pattern: ^(([0-8][0-9])|(9[0-5]))[0-9]{3}$
        - name: distance
          description: Filtre par distance du code insee
          in: query
          schema:
            type: integer
        - name: acte[]
          description: Filtre par actes couverts
          in: query
          schema:
            type: array
            items:
              $ref: "#/components/schemas/acte"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/espace-conseil"
        "400":
          description: Bad request
  /espaces-conseil/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Recherche un Espace France Rénov' par son numéro id
      tags:
        - Espace Conseil
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/espace-conseil"
        "400":
          description: Bad request
        "404":
          description: Not found
  /professionnels:
    get:
      summary: Recherche une liste de professionnels RGE
      description: Ce endpoint interroge l'opendata des entreprises RGE de l'ADEME
      tags:
        - Professionnel
      parameters:
        - name: code_insee
          description: Filtre par couverture géographique
          in: query
          schema:
            type: string
            pattern: ^(([0-8][0-9])|(9[0-5]))[0-9]{3}$
        - name: distance
          description: Filtre par distance du code insee
          in: query
          schema:
            type: integer
        - name: siren
          description: Filtre par numéro de SIREN
          in: query
          schema:
            $ref: "#/components/schemas/siren"
        - name: domaine_rge[]
          description: Filtre par domaines RGE couverts
          in: query
          schema:
            type: array
            items:
              $ref: "#/components/schemas/domaine_rge"
        - name: date
          description: Filtre par date de qualification RGE
          in: query
          schema:
            type: string
            format: date
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/professionnel"
        "400":
          description: Bad request
  /professionnels/{siret}:
    parameters:
      - name: siret
        description: Filtre par numéro de SIRET
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/siret"
      - name: date
        description: Filtre par date de qualification RGE
        in: query
        schema:
          type: string
          format: date
      - name: domaine_rge[]
        description: Filtre par domaines RGE couverts
        in: query
        schema:
          type: array
          items:
            $ref: "#/components/schemas/domaine_rge"
    get:
      summary: Recherche un professionnel par son numéro de SIRET
      tags:
        - Professionnel
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/professionnel"
        "400":
          description: Bad request
        "404":
          description: Not found
components:
  schemas:
    siren:
      title: Numéro de SIREN
      type: string
      pattern: ^[0-9]{9,9}$
    siret:
      title: Numéro de SIRET
      type: string
      pattern: ^[0-9]{14,14}$
    acte:
      title: Acte couvert par un Espace Conseil France Rénov'
      type: string
      oneOf:
        - const: "A01"
          title: Information de premier niveau
        - const: "A02"
          title: Conseil personalisé
        - const: "A03"
          title: Audit énergétique
        - const: "A04"
          title: Accompagnement travaux
        - const: "A4b"
          title: Accompagnement et suivi travaux
        - const: "A05"
          title: Assistance Maitrise d'Oeuvre
        - const: "B01"
          title: Information de premier niveau
        - const: "B02"
          title: Conseil personalisé
    domaine_rge:
      title: Domaine RGE
      type: string
      oneOf:
        - const: "21"
          title: Fenêtres, volets, portes extérieures 2020
        - const: "23"
          title: Isolation du toit 2020
        - const: "29"
          title: Projet complet de rénovation
        - const: "72"
          title: Audit énergétique
        - const: "73"
          title: Etude solaire thermique
        - const: "74"
          title: Etude solaire photovoltaïque
        - const: "75"
          title: Etude thermique reglementaire
        - const: "76"
          title: Etude forage géothermique
        - const: "77"
          title: Etude ACV
        - const: "78"
          title: Etude enveloppe du bâtiment
        - const: "79"
          title: Etude système technique bâtiment
        - const: "80"
          title: Etude bois énergie
        - const: "81"
          title: Etude eclairage
        - const: "82"
          title: Commisionnement
        - const: "83"
          title: Architecte
        - const: "85"
          title: Chaudière condensation ou micro-cogénération gaz ou fioul
        - const: "86"
          title: Chauffage et/ou eau chaude solaire
        - const: "87"
          title: Chaudière bois
        - const: "88"
          title: Poêle ou insert bois
        - const: "89"
          title: "Pompe à chaleur : chauffage"
        - const: "90"
          title: Chauffe-Eau Thermodynamique
        - const: "91"
          title: Radiateurs électriques, dont régulation.
        - const: "92"
          title: Ventilation mécanique
        - const: "93"
          title: Fenêtres, volets, portes donnant sur l'extérieur
        - const: "94"
          title: Fenêtres de toit
        - const: "95"
          title: Isolation par l'intérieur des murs ou rampants de toitures  ou plafonds
        - const: "96"
          title: Isolation des murs par l'extérieur
        - const: "97"
          title: Isolation des toitures terrasses ou des toitures par l'extérieur
        - const: "98"
          title: Isolation des combles perdus
        - const: "99"
          title: Isolation des planchers bas
        - const: "100"
          title: Forage géothermique
        - const: "101"
          title: Panneaux solaires photovoltaïques
    qualification:
      title: Qualification RGE
      type: object
      properties:
        code:
          title: Code de la qualification
          type: string
        nom:
          title: Nom de la qualification
          type: string
        domaines_rge:
          title: Liste des domaines RGE couverts
          type: array
          items:
            $ref: "#/components/schemas/domaine_rge"
        date_debut:
          title: Date de début de validité de la qualification
          type: string
          format: date
        date_fin:
          title: Date de fin de validité de la qualification
          type: string
          format: date
        attestation:
          title: URL d'accès à l'attestation de qualification
          type: string
      required:
        - code
        - nom
        - domaines_rge
        - date_debut
        - date_fin
        - attestation
    ban_adresse:
      title: Adresse au format BAN
      type: object
      properties:
        cle_interop:
          type: string
        commune_insee:
          type: string
        commune_nom:
          type: string
        voie_nom:
          type: string
        numero:
          type: string
        position:
          type: array
          items:
            type: number
        x:
          type: number
        y:
          type: number
      required:
        - cle_interop
        - commune_insee
        - commune_nom
        - voie_nom
        - numero
        - position
        - x
        - t
    accompagnateur:
      title: Accompagnateur
      description: Etablissement agréé Mon Accompagnateur Rénov'
      type: object
      properties:
        raison_sociale:
          title: Raison sociale
          type: string
        siren:
          $ref: "#/components/schemas/siren"
        siret:
          $ref: "#/components/schemas/siret"
        adresse:
          $ref: "#/components/schemas/ban_adresse"
        email:
          title: Email de contact
          type: string
          format: email
        telephone:
          title: Numéro de téléphone de contact
          type: string
        site_internet:
          title: Site internet de contact
          type: [string, "null"]
        date_debut_agrement:
          title: Date de début de l'agrément MAR
          type: string
          format: date
        date_fin_agrement:
          title: Date de fin de l'agrément MAR
          type: string
          format: date
      required:
        - raison_sociale
        - siren
        - siret
        - adresse
        - email
        - telephone
        - site_internet
        - date_debut_agrement
        - date_fin_agrement
    auditeur:
      title: Auditeur
      description: Entreprise qualifiée RGE - Audit énergétique
      type: object
      properties:
        raison_sociale:
          title: Raison sociale
          type: string
        siren:
          $ref: "#/components/schemas/siren"
        siret:
          $ref: "#/components/schemas/siret"
        adresse:
          $ref: "#/components/schemas/ban_adresse"
        email:
          title: Email de contact
          type: string
          format: email
        telephone:
          title: Numéro de téléphone de contact
          type: string
        site_internet:
          title: Site internet de contact
          type: [string, "null"]
        qualifications:
          title: Liste des qualifications RGE
          type: array
          items:
            $ref: "#/components/schemas/qualification"
      required:
        - raison_sociale
        - siren
        - siret
        - adresse
        - email
        - telephone
        - site_internet
        - qualifications
    espace-conseil:
      title: Espace Conseil
      description: Espaces Conseil France Renov
      type: object
      properties:
        id:
          title: Identifiant de la structure
          type: string
        raison_sociale:
          title: Raison sociale
          type: string
        adresse:
          $ref: "#/components/schemas/ban_adresse"
        email:
          title: Email de contact
          type: string
          format: email
        telephone:
          title: Numéro de téléphone de contact
          type: string
        site_internet:
          title: Site internet de contact
          type: [string, "null"]
        actes_couverts:
          title: Liste des actes couverts par l'espace conseil
          type: array
          items:
            $ref: "#/components/schemas/acte"
      required:
        - id
        - raison_sociale
        - adresse
        - email
        - telephone
        - site_internet
        - actes_couverts
    professionnel:
      title: Professionnel
      description: Entreprise qualifiée RGE
      type: object
      properties:
        raison_sociale:
          title: Raison sociale
          type: string
        siren:
          $ref: "#/components/schemas/siren"
        siret:
          $ref: "#/components/schemas/siret"
        adresse:
          $ref: "#/components/schemas/ban_adresse"
        email:
          title: Email de contact
          type: string
          format: email
        telephone:
          title: Numéro de téléphone de contact
          type: string
        site_internet:
          title: Site internet de contact
          type: [string, "null"]
        qualifications:
          title: Liste des qualifications RGE
          type: array
          items:
            $ref: "#/components/schemas/qualification"
      required:
        - raison_sociale
        - siren
        - siret
        - adresse
        - email
        - telephone
        - site_internet
        - qualifications
